[package]
name = "trevm"
version = "0.1.0"
edition = "2021"
authors = ["Init4 LLC"]
homepage = "https://github.com/init4tt/trevm"
repository = "https://github.com/init4tt/trevm"
license = "MIT OR APACHE-2.0"
description = "A typestate API wrapper for the revm EVM implementation"

[dependencies]
alloy-consensus = { version = "0.1", features = ["k256"] }
alloy-primitives = "0.7.6"
revm = { version = "11.0.0", default-features = false, features = ["std"] }

[dev-dependencies]
revm = { version = "11.0.0", features = ["test-utils", "serde-json", "alloydb", "std"] }
tokio = { version = "1.28", features = ["macros", "rt-multi-thread"] }
alloy-sol-types = { version = "0.7.7", default-features = false, features = [
    "std",
] }

# alloydb
alloy-provider = { version = "0.1" }
alloy-eips = { version = "0.1" }
alloy-transport = { version = "0.1" }

# misc
eyre = "0.6"

[features]
default = [
    "revm/std",
    "revm/c-kzg",
    "revm/blst",
    "revm/portable",
    "revm/secp256k1"
]

test-utils = ["revm/test-utils"]


secp256k1 = ["revm/secp256k1"]
c-kzg = ["revm/c-kzg"]
blst = ["revm/blst"]

portable = ["revm/portable"]

dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
    "optional_beneficiary_reward",
]

memory_limit = ["revm/memory_limit"]
optional_balance_check = ["revm/optional_balance_check"]
optional_beneficiary_reward = ["revm/optional_beneficiary_reward"]
optional_block_gas_limit = ["revm/optional_block_gas_limit"]
optional_eip3607 = ["revm/optional_eip3607"]
optional_gas_refund = ["revm/optional_gas_refund"]
optional_no_base_fee = ["revm/optional_no_base_fee"]
